server:
  port: 8765

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServerPeer1:7761/eureka/,http://eurekaServerPeer2:7762/eureka/,http://eurekaServerPeer3:7763/eureka/
