server:
  port: 8765

spring:
  application:
    name: service-hi
  sleuth:
    web:
      client:
        enabled: true
    sampler: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/  # 指定了 Zipkin 服务器的地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServerPeer1:7761/eureka/,http://eurekaServerPeer2:7762/eureka/,http://eurekaServerPeer3:7763/eureka/
