eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaServerPeer1:7761/eureka/,http://eurekaServerPeer2:7762/eureka/,http://eurekaServerPeer3:7763/eureka/
server:
  port: 9765
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true
